
Let's try out our R package. To do this, I'm going to recommend you create a special R file, sometimes called a "scratch file". It lives inside a folder called `inst`, which is typically not touched by R package building. This is a useful trick if you want to have a way to play around with some R code, keeping it inside your R package.

::: {.callout-note title="Workflow ideas: a scratch file" collapse="true"}
Sometimes you want to have a little scratch pad to write all your practice code. One place where you can do this is in a "scratch" file.

Create a scratch file:

1.  Create a directory `inst`
2.  Inside that directory, create an R file called `scratch.R` (note that this can actually be called anything, but `scratch.R` is what I use)
3.  Write `library(praiseme)` inside `scratch.R`
:::

Does this work for you?

Let's pick this up in the next section, "How to use extra packages"


## Demo in `scratch`

Now that we've done this, let's install the package, and then go to `scratch.R`

I then get this error:

```
> clean_education_data(raw_education_2014)
Error in clean_education_data(raw_education_2014) : 
  could not find function "clean_education_data"
```

However, if we do load all, with:

```r
load_all(".")
```

Then it works!

But what gives with the function not being available? Let's have a look inside `learned` by using `::`:

There's nothing in there! Now let's focus on getting that working, which will involve learning about **documenting our code!**



